###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

server:
  port: 8080

spring:
  application:
    name: app-xxl-sso

# 修改调用超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
