server:
  port: 9999

# 指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

# 服务的名称
spring:
  application:
    name: app-zuul
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite-member?useSSL=FALSE&serverTimezone=UTC

# 自定义路由映射
zuul:
  routes:
    api-a:
      path: /api-weixin/**
      serviceId: app-weixin
    api-b:
      path: /api-member/**
      serviceId: app-member
    api-c:
      path: /api-pays/**
      serviceId: app-pays

### mybatis 日志打印
logging:
  level:
    com.adminsys.mapper: debug

