server:
  port: 8080

# 指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

# 服务的名称
spring:
  application:
    name: app-zuul

# 自定义路由映射
zuul:
  routes:
    api-a:
      path: /api-weixin/**
      serviceId: app-weixin
    api-b:
      path: /api-member/**
      serviceId: app-member
    api-c:
      path: /api-pays/**
      serviceId: app-pays

