server:
  port: 8080

# 指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

# 服务的名称
spring:
  application:
    name: app-pays
    ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite-member?useSSL=FALSE&serverTimezone=UTC
    ###  redis配置
  redis:
    host: 127.0.0.1
    password: feise5328
    port: 6379
    ###  rabbitmq生产者配置
  rabbitmq:
    host: 114.116.224.100
    username: memo012
    password: 123456
    port: 5672
    virtual-host: /test
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true


# swagger 相关配置
swagger:
  base-package: com.adminsys.service
  title: 基于SpringCloud2.x构建微服务电商项目-会员服务接口
  version: 1.1
  terms-of-service-url: www.memo012.com
  contact:
    name: memo012
    email: 1158821459@qq.com

### mybatis 日志打印
logging:
  level:
    com.adminsys.dao: debug

###多线程配置
threadPool:
  ###核心线程数
  corePoolSize: 10
  ###最大线程数
  maxPoolSize: 20
  ##  队列容量
  queueCapacity: 16

